# Generated by Django 3.0.6 on 2020-05-04 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Benchmark')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.App')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_ms', models.IntegerField()),
                ('current', models.IntegerField()),
                ('voltage', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.App')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Task')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='benchmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Benchmark'),
        ),
    ]
