# Generated by Django 3.0.6 on 2020-05-05 15:03

from django.db import migrations, models
import energy.models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d', validators=[energy.models.validate_file_extension])),
            ],
        ),
    ]
