# Generated by Django 3.0.6 on 2020-05-05 15:52

import datetime
from django.db import migrations, models
import energy.models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_uploadfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
        migrations.AddField(
            model_name='benchmark',
            name='file',
            field=models.FileField(default=1, upload_to='files/%Y/%m/%d', validators=[energy.models.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
