# Generated by Django 3.0.6 on 2020-05-05 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_auto_20200505_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurements',
            new_name='Measurement',
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
