# Generated by Django 3.0.6 on 2020-05-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0005_auto_20200511_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('graph', models.FilePathField()),
                ('csv', models.FilePathField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.App')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Task')),
            ],
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='app',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='task',
        ),
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.AddField(
            model_name='measurement',
            name='result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='energy.Result'),
            preserve_default=False,
        ),
    ]
