# Generated by Django 3.0.6 on 2020-05-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_auto_20200511_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='current',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='energy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='time_ms',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='voltage',
            field=models.FloatField(),
        ),
    ]
