# Generated by Django 3.0.6 on 2020-05-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0008_result_benchmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='time_ms',
            new_name='time',
        ),
    ]
