# Generated by Django 3.0.6 on 2020-05-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0011_auto_20200512_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchmark',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='is_started',
        ),
        migrations.AddField(
            model_name='task',
            name='message',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('QU', 'QUEUED'), ('ST', 'STARTED'), ('FA', 'FAILED'), ('FI', 'FINISHED')], default='QU', max_length=2),
        ),
    ]
