# Generated by Django 3.0.6 on 2020-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0014_auto_20200512_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='csv',
            field=models.FilePathField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='graph',
            field=models.FilePathField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
