# Generated by Django 3.0.6 on 2020-05-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0015_auto_20200512_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
