# Generated by Django 3.0.6 on 2020-05-13 15:26

from django.db import migrations, models
import energy.models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0016_auto_20200512_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmark',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d', validators=[energy.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
