# Generated by Django 3.0.6 on 2020-06-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0018_auto_20200529_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmark',
            name='clear_cache',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='close_apps',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='exec_prog',
            field=models.CharField(choices=[('python', 'python 2.7.16 (androidViewClient)'), ('python3', 'python 3.7.4'), ('monkeyrunner', 'monkeyrunner'), ('java', 'Java 1.8.0_241-b07 (UI Automator)')], default='monkeyrunner', max_length=12),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='init',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='result',
            name='screenshot_path',
            field=models.FilePathField(blank=True, default=''),
        ),
    ]
