# Generated by Django 3.0.6 on 2020-06-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0020_auto_20200603_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='status',
            field=models.CharField(choices=[('QU', 'QUEUED'), ('ST', 'STARTED'), ('CC', 'CLEARING CHACHE'), ('CA', 'CLOSING APPS'), ('RI', 'RUNNING INIT SCRIPT'), ('RS', 'RUNNING SCRIPT'), ('SS', 'TAKING SCREENSHOT'), ('SD', 'SAVING DATA'), ('FA', 'FAILED'), ('FI', 'FINISHED')], default='QU', max_length=2),
        ),
    ]
